"""Pydantic schemas。命名与 `数据模型与接口契约V1.md` 保持一致。"""
from app.schemas.agent import (
    AgentProfile,
    AgentProfilePatch,
    AgentRuntimeState,
    CreatePlayerRequest,
    PlayerInteractRequest,
    PlayerInteractResponse,
    PlayerMoveRequest,
    PlayerMoveResponse,
    PlayerTalkRequest,
    PlayerTalkResponse,
    Relationship,
)
from app.schemas.memory import (
    Memory,
    MemorySearchRequest,
    MemorySearchResult,
)
from app.schemas.simulation import (
    AgentActionRead,
    Simulation,
    SimulationDeltaPayload,
    SimulationState,
    SimulationStateDelta,
    WorldEvent,
)
from app.schemas.world import (
    Bounds,
    DialogueMessage,
    Location,
    MapScene,
    MapTile,
    PathfindingRequest,
    PathfindingResponse,
    Portal,
    TilePosition,
    WorldObject,
)

__all__ = [
    "AgentActionRead",
    "AgentProfile",
    "AgentProfilePatch",
    "AgentRuntimeState",
    "Bounds",
    "CreatePlayerRequest",
    "DialogueMessage",
    "Location",
    "MapScene",
    "MapTile",
    "Memory",
    "MemorySearchRequest",
    "MemorySearchResult",
    "PathfindingRequest",
    "PathfindingResponse",
    "PlayerInteractRequest",
    "PlayerInteractResponse",
    "PlayerMoveRequest",
    "PlayerMoveResponse",
    "PlayerTalkRequest",
    "PlayerTalkResponse",
    "Portal",
    "Relationship",
    "Simulation",
    "SimulationDeltaPayload",
    "SimulationState",
    "SimulationStateDelta",
    "TilePosition",
    "WorldEvent",
    "WorldObject",
]
