#!/usr/bin/env python3
"""在 CI Runner 上根据环境变量生成服务器用的 .env（供 docker compose 使用）。

用法示例：
  DEPLOY_POSTGRES_PASSWORD=xxx DEPLOY_SSH_HOST=203.0.113.10 python scripts/write_deploy_env.py

必填：DEPLOY_POSTGRES_PASSWORD

可选：
  DEPLOY_CORS_ORIGIN — BACKEND_CORS_ORIGINS；不配则默认 http://{DEPLOY_SSH_HOST}:{FRONTEND_DEMO_PORT}
  DEPLOY_SSH_HOST — 与 GitHub Secret DEPLOY_HOST 相同即可；用于默认 CORS 与 BACKEND_PUBLIC_URL
  DEPLOY_LLM_API_KEY / DEPLOY_BACKEND_PUBLIC_URL / POSTGRES_* / FRONTEND_DEMO_PORT / BACKEND_PORT
"""

from __future__ import annotations

import os
import sys
from pathlib import Path
from urllib.parse import quote


def q(s: str) -> str:
    return quote(s, safe="")


def main() -> int:
    out = Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get("DEPLOY_ENV_OUT", ".env"))

    pg_user = os.environ.get("POSTGRES_USER", "virtual_town")
    pg_db = os.environ.get("POSTGRES_DB", "virtual_town")
    try:
        pg_pass = os.environ["DEPLOY_POSTGRES_PASSWORD"]
    except KeyError:
        print("ERROR: DEPLOY_POSTGRES_PASSWORD is required", file=sys.stderr)
        return 1

    llm_key = os.environ.get("DEPLOY_LLM_API_KEY", "").strip()
    ssh_host = os.environ.get("DEPLOY_SSH_HOST", "").strip()
    fe_port = os.environ.get("FRONTEND_DEMO_PORT", "8080")

    cors = os.environ.get("DEPLOY_CORS_ORIGIN", "").strip()
    if not cors:
        if not ssh_host:
            print(
                "ERROR: set DEPLOY_CORS_ORIGIN or DEPLOY_SSH_HOST (for default http://HOST:PORT)",
                file=sys.stderr,
            )
            return 1
        cors = f"http://{ssh_host}:{fe_port}"

    backend_pub = os.environ.get("DEPLOY_BACKEND_PUBLIC_URL", "").strip()
    if not backend_pub:
        bport = os.environ.get("BACKEND_PORT", "8000")
        backend_pub = f"http://{ssh_host}:{bport}" if ssh_host else f"http://localhost:{bport}"

    u, p = q(pg_user), q(pg_pass)
    db_async = f"postgresql+asyncpg://{u}:{p}@postgres:5432/{pg_db}"
    db_sync = f"postgresql+psycopg://{u}:{p}@postgres:5432/{pg_db}"

    be_port = os.environ.get("BACKEND_PORT", "8000")

    text = f"""# Generated by CI (write_deploy_env.py) — do not commit
APP_ENV=prod
APP_NAME=virtual-town
APP_LOG_LEVEL=INFO
APP_DEBUG=false

BACKEND_HOST=0.0.0.0
BACKEND_PORT={be_port}
BACKEND_PUBLIC_URL={backend_pub}
BACKEND_CORS_ORIGINS={cors}

POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB={pg_db}
POSTGRES_USER={pg_user}
POSTGRES_PASSWORD={pg_pass}
DATABASE_URL={db_async}
DATABASE_URL_SYNC={db_sync}
DATABASE_URL_LOCAL=
DATABASE_URL_LOCAL_SYNC=

REDIS_HOST=redis
REDIS_PORT=6379
REDIS_DB=0
REDIS_URL=redis://redis:6379/0
REDIS_URL_LOCAL=

LLM_PROVIDER=dashscope
LLM_BASE_URL=https://dashscope.aliyuncs.com/compatible-mode/v1
LLM_API_KEY={llm_key}
LLM_CHAT_MODEL=qwen-plus
LLM_REASONING_MODEL=qwen-plus
LLM_EMBEDDING_MODEL=text-embedding-v3
LLM_EMBEDDING_DIM=1024
LLM_CHAT_TIMEOUT_SECONDS=30
LLM_MAX_RETRIES=2
LLM_ENABLED={"true" if llm_key else "false"}
LLM_DIALOGUE_MODEL=
LLM_PLANNING_MODEL=
LLM_QUERY_REWRITE_MODEL=

OLLAMA_ENABLED=false
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_CHAT_MODEL=qwen2.5:7b
OLLAMA_EMBEDDING_MODEL=nomic-embed-text
OLLAMA_EMBEDDING_DIM=768
OLLAMA_TIMEOUT_SECONDS=60
LLM_PROVIDER_PRIORITY=dashscope

SOCIAL_NEED_TRIGGER_THRESHOLD=40
NPC_DIALOG_MAX_TURNS=10
INTERACTION_REQUEST_TIMEOUT_SECONDS=30
SOCIAL_COOLDOWN_AFTER_REFUSAL_MINUTES=30
INTERACTION_STRANGER_FAMILIARITY_THRESHOLD=0.2
INTERACTION_HIGH_PRIORITY_THRESHOLD=8

MEMORY_PROJECTION_ENABLED=true
MEMORY_PROJECTION_DEFAULT_MIN_IMPORTANCE=2
MEMORY_PROJECTION_DEFAULT_DEBOUNCE_MINUTES=30
MEMORY_CONSOLIDATION_ENABLED=true
MEMORY_CONSOLIDATION_MIN_BUCKET_SIZE=3
MEMORY_CONSOLIDATION_LOOKBACK_DAYS=7
MEMORY_RUMINATION_ENABLED=true
MEMORY_RUMINATION_IMPORTANCE_THRESHOLD=7
MEMORY_RUMINATION_SAMPLE_SIZE=5
MEMORY_DIALOGUE_PER_MESSAGE=true

NEEDS_SOCIAL_GROWTH_PER_MINUTE=0.0030
NEEDS_HUNGER_GROWTH_PER_MINUTE=0.0020
NEEDS_ENERGY_DECAY_PER_MINUTE=0.0015
NEEDS_SOCIAL_DECAY_AFTER_CHAT=0.55
SOCIAL_ENCOUNTER_SCAN_MINUTES=2
SOCIAL_ENCOUNTER_DISTANCE=5
SOCIAL_ENCOUNTER_COOLDOWN_MINUTES=10

WORLD_GEN_OUTDOOR_DEFAULT_WIDTH=120
WORLD_GEN_OUTDOOR_DEFAULT_HEIGHT=90
SIMULATION_WORLD_TICK_HZ=2
SIMULATION_AI_TICK_MINUTES=3
SIMULATION_SPEED_DEFAULT=1
SIMULATION_AUTOSTART=false
SIMULATION_RESET_QUEUE_ON_START=true

TASK_QUEUE_MODE=async
TASK_QUEUE_BACKEND=rq
TASK_QUEUE_HIGH=vt:high
TASK_QUEUE_DEFAULT=vt:default
TASK_QUEUE_LOW=vt:low
TASK_QUEUE_WORKER_COUNT=1
TASK_QUEUE_WORKER_CONCURRENCY=18
AGENT_DECISION_DEADLINE_SECONDS=105

OBSERVABILITY_FLUSH_INTERVAL=2
OBSERVABILITY_BATCH_SIZE=280
OBSERVABILITY_BUFFER_MAX_SIZE=4000

SECURITY_PLAYER_RATE_LIMIT=1
SECURITY_RATE_WINDOW_SECONDS=1
SECURITY_IP_RATE_LIMIT=20
SECURITY_IP_RATE_WINDOW_SECONDS=1
SECURITY_MAX_MESSAGE_LENGTH=500
SECURITY_TOOL_VIOLATION_THRESHOLD=5
SECURITY_TOOL_VIOLATION_WINDOW_SECONDS=300

VITE_API_BASE_URL=
VITE_WS_BASE_URL=
FRONTEND_DEMO_PORT={fe_port}
VITE_AGENT_MOVE_TWEEN_MS=145
"""
    out.write_text(text, encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
